# Basic configuration for Air
[build]
  # Output path for the binary that will be executed
  bin = "bin/main"
  # Command to compile the code
  cmd = "go build -o ./bin/main ./main.go"
  # Directories or files that trigger a reload
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "bin"]

[runner]
  # Command that will be run to execute the binary
  cmd = "./bin/main"