version: '3.8'

services:
  web:
    build: .
    container_name: go-web
    command: air serve
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=taxi
      - POSTGRES_DB=postgres

      - AIR_ENV=development

      - GO_ENV=development
      - AIR_CONF=.air.toml

      - JWT_SECRET_KEY="SX"

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
